# Generated by Django 3.0.1 on 2020-01-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Workout_Name', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='')),
                ('Username', models.CharField(default='anonymous', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('Workout_Description', models.TextField(default='DataFlair Django tutorials')),
            ],
        ),
    ]
